import { FetchedMeeting } from "types/MeetingTypes";
import { ChatComponent } from "./ChatComponent";

type Props = {
  meeting: FetchedMeeting;
};

export const MeetingChat = ({ meeting }: Props) => {
  return (
    <div>
      <dt className="text-md font-extrabold leading-6 text-gray-50 mt-6">
        Ask further questions
        <span className="text-sm ml-2 font-normal text-gray-500">
          - Gemini chat
        </span>
      </dt>
      <ChatComponent
        systemPrompt={`We are here to discuss this meeting: ${JSON.stringify(
          meeting
        )} if an enviromental report exists, then it's generated by you and here are my following questions. `}
      />
    </div>
  );
};
